//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvEntityProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Contact
    {
        public int ID { get; set; }
        public string fullName { get; set; }
        public string mail { get; set; }
        public string message { get; set; }
        public string topic { get; set; }
    }
}
