//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvEntityProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Address
    {
        public byte ID { get; set; }
        public string phoneNumber { get; set; }
        public string mail { get; set; }
        public string address { get; set; }
        public string location { get; set; }
    }
}
